language: python

python:
    - 2.7

before_install:
    - sudo apt-get install python-numpy

install:
    - pip install nose
    - pip install coverage
    - pip install .

script:
    - python setup.py nosetests -s -x
