language: python

before_script:
    - sudo apt-get update
    - sudo apt-get install llvm-2.9-dev clang

python:
    - 2.7

install:
    - pip install nose
    - pip install coverage
    - pip install .

script:
    - export NOS_LLVM_VERSION=2.9
    - export NOS_LLC=llc-2.9
    - python setup.py nosetests -s
